module.exports = {
  random_user_mock: [
    {
      id: 157,
      favorite: false,
      course: "math",
      bg_color: "red",
      note: `this is a note for user this is a note for user this is a note for user this is a note for  user this is a note for  user this is a note for  user this is a note for  user this is a note for user`,
      gender: "male",
      title: "Mr",
      full_name: "Norbert Weishaupt",
      city: "Rhön-Grabfeld",
      state: "Mecklenburg-Vorpommern",
      country: "Germany",
      postcode: 52640,
    },
    {
      id: 2,
      favorite: false,
      course: "math",
      bg_color: "blue",
      note: `this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user`,
      gender: "female",
      title: "Ms",
      full_name: "Mary Silva",
      city: "",
      state: "Mecklenburg-Vorpommern",
      // Kyrgyzstan
      country: "Germany",
      postcode: 52640,
      coordinates: { latitude: "-42.1817", longitude: "-152.1685" },
      timezone: { offset: "+9:30", description: "Adelaide, Darwin" },
    },
    {
      id: 3,
      favorite: false,
      course: "math",
      bg_color: "black",
      note: `this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user`,
      gender: "male",
      title: "Mr",
      full_name: "Noah Davis",
      city: "São Paulo",
      state: "Mecklenburg-Vorpommern",
      country: "Brazil",
      postcode: 52640,
      coordinates: { latitude: "-42.1817", longitude: "-152.1685" },
      timezone: { offset: "+9:30", description: "Adelaide, Darwin" },
      email: "noah.davis@example.com",
      b_date: "1956-12-23T19:09:19.602Z",
      age: 35,
      phone: "(111)-624-4089",
      picture_large: "https://randomuser.me/api/portraits/men/11.jpg",
      picture_thumbnail: "https://randomuser.me/api/portraits/thumb/men/11.jpg",
    },
    {
      id: 4,
      favorite: false,
      course: "math",
      bg_color: "yellow",
      note: `this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user`,
      gender: "female",
      title: "Ms",
      full_name: "Tracey Bell",
      city: "Split",
      state: "Mecklenburg-Vorpommern",
      country: "Croatia",
      postcode: 52640,
      coordinates: { latitude: "-42.1817", longitude: "-152.1685" },
      timezone: { offset: "+9:30", description: "Adelaide, Darwin" },
      email: "tracey.bell@example.com",
      b_date: "1956-12-23T19:09:19.602Z",
      age: 20,
      phone: "079-08291509",
      picture_large: "https://randomuser.me/api/portraits/men/22.jpg",
      picture_thumbnail: "https://randomuser.me/api/portraits/thumb/men/22.jpg",
    },
    {
      id: 5,
      favorite: true,
      course: "math",
      bg_color: "green",
      note: `this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user`,
      gender: "female",
      title: "Ms",
      full_name: "Gabriella Peck",
      city: "San Francisco",
      state: "Mecklenburg-Vorpommern",
      country: "United States",
      postcode: 52640,
      coordinates: { latitude: "-42.1817", longitude: "-152.1685" },
      timezone: { offset: "+9:30", description: "Adelaide, Darwin" },
      email: "norbert.weishaupt@example.com",
      b_date: "1956-12-23T19:09:19.602Z",
      age: 31,
      phone: "079-08291509",
      picture_large: "https://randomuser.me/api/portraits/men/25.jpg",
      picture_thumbnail: "https://randomuser.me/api/portraits/thumb/men/25.jpg",
    },
    {
      id: 7,
      favorite: true,
      course: "math",
      bg_color: "green",
      note: `this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user this is a note for ${this.id} user`,
      gender: "female",
      title: "Ms",
      full_name: "AAAAAAAAAAAAAA Peck",
      city: "San Francisco",
      state: "Mecklenburg-Vorpommern",
      country: "United States",
      postcode: 52640,
      coordinates: { latitude: "-42.1817", longitude: "-152.1685" },
      timezone: { offset: "+9:30", description: "Adelaide, Darwin" },
      email: "norbert.weishaupt@example.com",
      b_date: "1956-12-23T19:09:19.602Z",
      age: 31,
      phone: "079-08291509",
      picture_large: "https://randomuser.me/api/portraits/men/25.jpg",
      picture_thumbnail: "https://randomuser.me/api/portraits/thumb/men/25.jpg",
    },
  ],
};
